import os
from pprint import pprint
from dotenv import set_key, unset_key


def set_playlist_name(new_name):
    if os.getenv("DISCOVER_EVERYWEEK_NAME")!=new_name:
        set_key(dotenv_path=".env",key_to_set="DISCOVER_EVERYWEEK_NAME",value_to_set=new_name)
        unset_key(dotenv_path=".env",key_to_unset="DISCOVER_EVERYWEEK_ID")


def copy_one_playlist_to_another(spotify_client, move_from_id, move_to_id):
    moving_from_playlist = spotify_client.playlist(move_from_id, fields="tracks")
    print("MOVE TO ID ",move_to_id)
    moving_to_playlist = spotify_client.playlist(move_to_id, fields="tracks")
    full_traklist_uris = [tr['uri'] for tr in [track['track'] for track in moving_to_playlist['tracks']['items']]]
    tracklist_to_add = [tr['uri'] for tr in [track['track'] for track in moving_from_playlist['tracks']['items']]]
    songs_to_add = [song_uri for song_uri in tracklist_to_add if song_uri not in full_traklist_uris]
    print(">>INFO: Adding songs to big playlist...")
    pprint(songs_to_add)
    if len(songs_to_add) > 0:
        spotify_client.playlist_add_items(move_to_id, songs_to_add)


def get_discover_weekly(spotify_client, discover_weekly_name = "Discover Weekly"):
    if os.getenv("DISCOVER_WEEKLY_ID"):
        return os.getenv("DISCOVER_WEEKLY_ID")
    all_user_playlists = spotify_client.current_user_playlists()
    for playlist in all_user_playlists['items']:
        if playlist['name'] == discover_weekly_name:
            playlist_id = playlist['id']
            set_key(dotenv_path=".env",key_to_set="DISCOVER_WEEKLY_ID",value_to_set=playlist_id)
            return playlist_id


def get_or_create_playlist(spotify_client, name):
    if os.getenv("DISCOVER_EVERYWEEK_ID") and os.getenv('DISCOVER_EVERYWEEK_NAME'):
        if os.getenv('DISCOVER_EVERYWEEK_NAME') == name:
            return os.getenv("DISCOVER_EVERYWEEK_ID")
    else:
        return create_new_playlist(spotify_client, name)
    

def create_new_playlist(spotify_client, name):
    created_playlist = spotify_client.user_playlist_create(spotify_client.current_user()['id'], name=name, public=False, collaborative=False, description="Playlist generated by discover-everyweek")
    set_key(dotenv_path=".env",key_to_set="DISCOVER_EVERYWEEK_ID",value_to_set=created_playlist['id'])
    set_key(dotenv_path=".env",key_to_set="DISCOVER_EVERYWEEK_NAME",value_to_set=name)
    return created_playlist['id']

